<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="xunit.v3.assert" PrivateAssets="all" />
    <PackageReference Include="xunit.v3.extensibility.core" PrivateAssets="all" />
  </ItemGroup>

</Project>
