<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Skopka.Chat.Transport.Http\Skopka.Chat.Transport.Http.csproj" />
    <PackageReference Include="SharpFuzz" />
  </ItemGroup>

</Project>
