<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Skopka.Chat.Attachments\Skopka.Chat.Attachments.csproj" />
    <ProjectReference Include="..\..\src\Skopka.Chat.Client\Skopka.Chat.Client.csproj" />
    <ProjectReference Include="..\..\src\Skopka.Chat.Server\Skopka.Chat.Server.csproj" />
    <ProjectReference Include="..\..\src\Skopka.Chat.Server.NSec\Skopka.Chat.Server.NSec.csproj" />
    <ProjectReference Include="..\..\src\Skopka.Chat.Server.AspNetCore\Skopka.Chat.Server.AspNetCore.csproj" />
    <ProjectReference Include="..\..\src\Skopka.Chat.Persistence.PostgreSql\Skopka.Chat.Persistence.PostgreSql.csproj" />
    <ProjectReference Include="..\..\src\Skopka.Chat.UI.Core\Skopka.Chat.UI.Core.csproj" />
  </ItemGroup>

</Project>
