using System.Diagnostics;
using System.Security.Cryptography;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Text.Json.Serialization.Metadata;
using Microsoft.AspNetCore.DataProtection;
using Skopka.Chat.Client;
using Skopka.Chat.Protocol;

namespace Skopka.Chat.Bots.AspNetCore;

/// <summary>
/// Create-only device keys and leased metadata protected by host-configured ASP.NET Data Protection.
/// The host MUST independently protect/persist the key ring (for example with a mounted certificate),
/// use a local access-controlled filesystem, and retain the installation scope across restarts.
/// </summary>
public sealed class ProtectedFileBotIdentityStore : IDeviceKeyStore, IDeviceIdentityMetadataStore
{
    private readonly string _directory;
    private readonly DeviceIdentityScope _scope;
    private readonly IDataProtector _protector;

    /// <summary>Creates an adapter for one account/installation; no identity is generated by construction.</summary>
    public ProtectedFileBotIdentityStore(string protectedDirectory, DeviceIdentityScope scope, IDataProtectionProvider protection)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(protectedDirectory);
        _scope = scope ?? throw new ArgumentNullException(nameof(scope));
        ArgumentNullException.ThrowIfNull(protection);
        _directory = Path.Combine(Path.GetFullPath(protectedDirectory), scope.StoragePartition);
        _protector = protection.CreateProtector("Skopka.Chat.BotIdentity.v1", scope.StoragePartition);
    }

    /// <inheritdoc />
    public async ValueTask<bool> TryCreateAsync(DeviceKeyMaterial material, CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(material);
        if (material.UserId != _scope.UserId || material.DeviceId.Value == Guid.Empty || material.KeyId.Value == Guid.Empty)
        {
            throw new ArgumentException("The bot identity scope is invalid.", nameof(material));
        }
        var dto = new KeyRecord(1, material.UserId.Value, material.DeviceId.Value, material.KeyId.Value,
            material.ExportEncryptionPrivateKey(), material.ExportSigningPrivateKey());
        try
        {
            if (dto.Encryption.Length is < 1 or > 512 || dto.Signing.Length is < 1 or > 512) { throw Corrupt(); }
            return await WriteAsync(KeyFile(material.DeviceId), dto, BotIdentityJson.Default.KeyRecord, false, cancellationToken).ConfigureAwait(false);
        }
        finally
        {
            CryptographicOperations.ZeroMemory(dto.Encryption);
            CryptographicOperations.ZeroMemory(dto.Signing);
        }
    }

    /// <summary>Replacement is deliberately unsupported; explicit recovery must use a separate identity.</summary>
    public ValueTask SaveAsync(DeviceKeyMaterial material, CancellationToken cancellationToken = default) =>
        throw new NotSupportedException("Bot identity keys cannot be overwritten.");

    /// <inheritdoc />
    public async ValueTask<DeviceKeyMaterial?> LoadAsync(DeviceId deviceId, CancellationToken cancellationToken = default)
    {
        var dto = await ReadAsync(KeyFile(deviceId), BotIdentityJson.Default.KeyRecord, cancellationToken).ConfigureAwait(false);
        if (dto is null) { return null; }
        try
        {
            if (dto.Version != 1 || dto.UserId != _scope.UserId.Value || dto.DeviceId != deviceId.Value || dto.KeyId == Guid.Empty ||
                dto.Encryption.Length is < 1 or > 512 || dto.Signing.Length is < 1 or > 512) { throw Corrupt(); }
            return new(new(dto.UserId), deviceId, new(dto.KeyId), dto.Encryption, dto.Signing);
        }
        finally
        {
            CryptographicOperations.ZeroMemory(dto.Encryption);
            CryptographicOperations.ZeroMemory(dto.Signing);
        }
    }

    /// <inheritdoc />
    public ValueTask DeleteAsync(DeviceId deviceId, CancellationToken cancellationToken = default) =>
        DeleteFileAsync(KeyFile(deviceId), cancellationToken);

    /// <inheritdoc />
    public async ValueTask<IDeviceIdentityLease> AcquireAsync(DeviceIdentityScope scope, CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(scope);
        if (scope.StoragePartition != _scope.StoragePartition) { throw new ArgumentException("The bot identity scope is invalid.", nameof(scope)); }
        var elapsed = Stopwatch.StartNew();
        while (true)
        {
            cancellationToken.ThrowIfCancellationRequested();
            try
            {
                Directory.CreateDirectory(_directory);
                var stream = new FileStream(Path.Combine(_directory, "identity.lock"), FileMode.OpenOrCreate,
                    FileAccess.ReadWrite, FileShare.None, 1, FileOptions.Asynchronous);
                return new Lease(this, stream);
            }
            catch (IOException) when (elapsed.Elapsed < TimeSpan.FromSeconds(10))
            {
                await Task.Delay(TimeSpan.FromMilliseconds(25), cancellationToken).ConfigureAwait(false);
            }
            catch (Exception exception) when (exception is IOException or UnauthorizedAccessException or System.Security.SecurityException)
            {
                throw Unavailable();
            }
        }
    }

    private static string KeyFile(DeviceId device)
    {
        if (device.Value == Guid.Empty) { throw new ArgumentException("The bot device is invalid.", nameof(device)); }
        return device.Value.ToString("N") + ".keys";
    }

    private async ValueTask<T?> ReadAsync<T>(string file, JsonTypeInfo<T> type, CancellationToken cancellationToken) where T : class
    {
        byte[]? plaintext = null;
        try
        {
            await using var stream = new FileStream(Path.Combine(_directory, file), FileMode.Open, FileAccess.Read,
                FileShare.Read | FileShare.Delete, 4096, FileOptions.Asynchronous);
            if (stream.Length is < 1 or > 16384) { throw Corrupt(); }
            var ciphertext = new byte[checked((int)stream.Length)];
            await stream.ReadExactlyAsync(ciphertext, cancellationToken).ConfigureAwait(false);
            if (stream.ReadByte() != -1) { throw Corrupt(); }
            plaintext = _protector.CreateProtector(file).Unprotect(ciphertext);
            if (plaintext.Length > 8192) { throw Corrupt(); }
            return JsonSerializer.Deserialize(plaintext, type) ?? throw Corrupt();
        }
        catch (FileNotFoundException) { return null; }
        catch (DirectoryNotFoundException) { return null; }
        catch (Exception exception) when (exception is CryptographicException or JsonException or ArgumentException or EndOfStreamException)
        {
            throw Corrupt();
        }
        catch (Exception exception) when (exception is IOException or UnauthorizedAccessException or System.Security.SecurityException)
        {
            throw Unavailable();
        }
        finally { if (plaintext is not null) { CryptographicOperations.ZeroMemory(plaintext); } }
    }

    private async ValueTask<bool> WriteAsync<T>(string file, T value, JsonTypeInfo<T> type, bool overwrite, CancellationToken cancellationToken)
    {
        byte[]? plaintext = null;
        var temporary = Path.Combine(_directory, Guid.NewGuid().ToString("N") + ".tmp");
        try
        {
            cancellationToken.ThrowIfCancellationRequested();
            Directory.CreateDirectory(_directory);
            plaintext = JsonSerializer.SerializeToUtf8Bytes(value, type);
            if (plaintext.Length > 8192) { throw Corrupt(); }
            var encrypted = _protector.CreateProtector(file).Protect(plaintext);
            await using (var stream = new FileStream(temporary, FileMode.CreateNew, FileAccess.Write,
                FileShare.None, 4096, FileOptions.Asynchronous | FileOptions.WriteThrough))
            {
                await stream.WriteAsync(encrypted, cancellationToken).ConfigureAwait(false);
                stream.Flush(flushToDisk: true);
            }
            cancellationToken.ThrowIfCancellationRequested();
            var destination = Path.Combine(_directory, file);
            try { File.Move(temporary, destination, overwrite); }
            catch (IOException) when (!overwrite && File.Exists(destination)) { return false; }
            return true;
        }
        catch (Exception exception) when (exception is IOException or UnauthorizedAccessException or CryptographicException or System.Security.SecurityException)
        {
            throw Unavailable();
        }
        finally
        {
            if (plaintext is not null) { CryptographicOperations.ZeroMemory(plaintext); }
            try { File.Delete(temporary); }
            catch (IOException) { }
            catch (UnauthorizedAccessException) { }
        }
    }

    private ValueTask DeleteFileAsync(string file, CancellationToken cancellationToken)
    {
        cancellationToken.ThrowIfCancellationRequested();
        try { File.Delete(Path.Combine(_directory, file)); }
        catch (Exception exception) when (exception is IOException or UnauthorizedAccessException or System.Security.SecurityException)
        {
            throw Unavailable();
        }
        return ValueTask.CompletedTask;
    }

    private sealed class Lease(ProtectedFileBotIdentityStore owner, FileStream stream) : IDeviceIdentityLease
    {
        private bool _disposed;
        public async ValueTask<DeviceIdentityMetadata?> ReadAsync(CancellationToken cancellationToken = default)
        {
            ObjectDisposedException.ThrowIf(_disposed, this);
            var dto = await owner.ReadAsync("identity.metadata", BotIdentityJson.Default.MetadataRecord, cancellationToken).ConfigureAwait(false);
            if (dto is null) { return null; }
            if (dto.Version != 1 || dto.DeviceId == Guid.Empty || dto.KeyId == Guid.Empty || dto.CreatedAt == default ||
                (dto.Encryption is null) != (dto.Signing is null) || (dto.Registered && dto.Encryption is null)) { throw Corrupt(); }
            PublicDevice? device = null;
            if (dto.Encryption is not null)
            {
                if (dto.Encryption.Length != 32 || dto.Signing!.Length != 32 || dto.RegisteredAt is null) { throw Corrupt(); }
                device = new(owner._scope.UserId, new(dto.DeviceId), new(dto.KeyId), dto.Encryption, dto.Signing, dto.RegisteredAt.Value);
                try { ProtocolValidator.Validate(device); }
                catch (ArgumentException) { throw Corrupt(); }
            }
            else if (dto.RegisteredAt is not null) { throw Corrupt(); }
            return new(1, owner._scope, new(dto.DeviceId), new(dto.KeyId), dto.CreatedAt, device, dto.Registered, dto.Revoked);
        }

        public async ValueTask WriteAsync(DeviceIdentityMetadata metadata, CancellationToken cancellationToken = default)
        {
            ObjectDisposedException.ThrowIf(_disposed, this);
            ArgumentNullException.ThrowIfNull(metadata);
            if (metadata.Version != 1 || metadata.Scope.StoragePartition != owner._scope.StoragePartition ||
                metadata.DeviceId.Value == Guid.Empty || metadata.KeyId.Value == Guid.Empty || metadata.CreatedAt == default ||
                (metadata.Registered && metadata.PublicDevice is null)) { throw Corrupt(); }
            if (metadata.PublicDevice is { } device)
            {
                if (device.UserId != owner._scope.UserId || device.DeviceId != metadata.DeviceId || device.KeyId != metadata.KeyId || device.IsRevoked) { throw Corrupt(); }
                ProtocolValidator.Validate(device);
            }
            var dto = new MetadataRecord(1, metadata.DeviceId.Value, metadata.KeyId.Value, metadata.CreatedAt,
                metadata.PublicDevice?.RegisteredAt, metadata.Registered, metadata.Revoked,
                metadata.PublicDevice is null ? null : metadata.PublicDevice.EncryptionPublicKey.ToArray(),
                metadata.PublicDevice is null ? null : metadata.PublicDevice.SigningPublicKey.ToArray());
            _ = await owner.WriteAsync("identity.metadata", dto, BotIdentityJson.Default.MetadataRecord, true, cancellationToken).ConfigureAwait(false);
        }

        public ValueTask DeleteAsync(CancellationToken cancellationToken = default)
        {
            ObjectDisposedException.ThrowIf(_disposed, this);
            return owner.DeleteFileAsync("identity.metadata", cancellationToken);
        }

        public async ValueTask DisposeAsync()
        {
            if (_disposed) { return; }
            _disposed = true;
            await stream.DisposeAsync().ConfigureAwait(false);
        }
    }

    private static DeviceIdentityStorageException Corrupt() => new(PersistentDeviceIdentityState.Corrupt);
    private static DeviceIdentityStorageException Unavailable() => new(PersistentDeviceIdentityState.Unavailable);
}

internal sealed record KeyRecord(int Version, Guid UserId, Guid DeviceId, Guid KeyId, byte[] Encryption, byte[] Signing)
{
    public override string ToString() => "KeyRecord([REDACTED])";
}
internal sealed record MetadataRecord(int Version, Guid DeviceId, Guid KeyId, DateTimeOffset CreatedAt,
    DateTimeOffset? RegisteredAt, bool Registered, bool Revoked, byte[]? Encryption, byte[]? Signing);

[JsonSourceGenerationOptions(GenerationMode = JsonSourceGenerationMode.Metadata, AllowDuplicateProperties = false, UnmappedMemberHandling = JsonUnmappedMemberHandling.Disallow,
    RespectNullableAnnotations = true, RespectRequiredConstructorParameters = true, MaxDepth = 16)]
[JsonSerializable(typeof(KeyRecord))]
[JsonSerializable(typeof(MetadataRecord))]
internal sealed partial class BotIdentityJson : JsonSerializerContext;
